spring.application.name=turnos

# Configuración del servidor
server.port=9002

# Configuración de la Base de Datos (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/servicio_turnos?serverTimezone=UTC
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# URL del microservicio de pacientes
pacientes.service.url=${PACIENTES_SERVICE_URL:http://localhost:9001}
